### ISSUE TITLE
Googles CSS Style Guide

### ISSUE THREAD

**Issue by zannain** [JoeSera/f1-3-c2p1-colmar-academy#3]
When you are writing styles that apply to multiple selectors, CSS Style guides such as [this](https://google.github.io/styleguide/htmlcssguide.html#Selector_and_Declaration_Separation) recommend separating each selector on its own line to improve [readability](https://github.com/JoeSera/f1-3-c2p1-colmar-academy/blob/master/Colmar/resources/css/style.css#L441-L454).

```css
/* Not best practice */
#checkbox1, #checkbox2, #checkbox3, #checkbox4, #checkbox5, #checkbox6 {
  opacity: 0;
}

/* Best practice */
#checkbox1,
#checkbox2, 
#checkbox3, 
#checkbox4,
#checkbox5, 
#checkbox6 {
  opacity: 0;
}
```
